const GAMES = [
  {
    id: 'coffee-2026-05-02',
    title: 'Roast Runner',
    description: 'Keep the beans moving through the roaster! Dodge hotspots, control airflow, and eject each batch at the perfect roast level.',
    category: 'action',
    thumbnail: 'linear-gradient(135deg, #bf360c 0%, #ff7043 100%)',
    file: 'games/coffee-2026-05-02.html',
    difficulty: 'Hard',
    emoji: '🔥',
    createdAt: '2026-05-02',
  },

  {
    id: 'caffeine-catch',
    title: 'Caffeine Catch',
    description: 'Catch falling coffee beans, cups, and espresso shots in your mug. But watch out for decaf and ice cubes! Speed increases as you level up.',
    category: 'action',
    thumbnail: 'linear-gradient(135deg, #6F4E37 0%, #C4A882 100%)',
    file: 'games/caffeine-catch.html',
    difficulty: 'Medium',
    emoji: '\u2615',
    createdAt: '2026-05-01',
  },
  {
    id: 'snake',
    title: 'Snake',
    description: 'The classic snake game! Eat food to grow longer, but don\'t hit the walls or your own tail. Simple yet addictive.',
    category: 'classic',
    thumbnail: 'linear-gradient(135deg, #2ecc71 0%, #27ae60 100%)',
    file: 'games/snake.html',
    difficulty: 'Easy',
    emoji: '\ud83d\udc0d',
    createdAt: '2026-04-15',
  },
  {
    id: 'memory-match',
    title: 'Memory Match',
    description: 'Test your memory by matching pairs of cards. Flip two at a time and find all matching pairs to win!',
    category: 'puzzle',
    thumbnail: 'linear-gradient(135deg, #e74c3c 0%, #c0392b 100%)',
    file: 'games/memory.html',
    difficulty: 'Easy',
    emoji: '\ud83c\udccf',
    createdAt: '2026-04-14',
  },
  {
    id: 'pong',
    title: 'Pong',
    description: 'The original arcade classic! Challenge a friend in this 2-player paddle game. First to score wins the round.',
    category: 'classic',
    thumbnail: 'linear-gradient(135deg, #3498db 0%, #2980b9 100%)',
    file: 'games/pong.html',
    difficulty: 'Medium',
    emoji: '\ud83c\udfd3',
    createdAt: '2026-04-13',
  },
  {
    id: 'flappy-bird',
    title: 'Flappy Bird',
    description: 'Navigate through endless pipes by tapping to flap. Seems easy? Think again! One of the hardest casual games ever.',
    category: 'action',
    thumbnail: 'linear-gradient(135deg, #1abc9c 0%, #16a085 100%)',
    file: 'games/flappy.html',
    difficulty: 'Hard',
    emoji: '\ud83d\udc26',
    createdAt: '2026-04-12',
  },
  {
    id: 'tic-tac-toe',
    title: 'Tic Tac Toe',
    description: 'Classic strategy game against an unbeatable AI. Can you outsmart the computer and force a draw \u2014 or even win?',
    category: 'strategy',
    thumbnail: 'linear-gradient(135deg, #9b59b6 0%, #8e44ad 100%)',
    file: 'games/tictactoe.html',
    difficulty: 'Easy',
    emoji: '\u274c',
    createdAt: '2026-04-11',
  },
  {
    id: 'breakout',
    title: 'Breakout',
    description: 'Smash bricks with a bouncing ball and paddle. Clear all the bricks to advance. A timeless arcade favorite!',
    category: 'action',
    thumbnail: 'linear-gradient(135deg, #f39c12 0%, #e67e22 100%)',
    file: 'games/breakout.html',
    difficulty: 'Medium',
    emoji: '\ud83e\uddf1',
    createdAt: '2026-04-10',
  },
  {
    id: '2048',
    title: '2048',
    description: 'Slide numbered tiles to combine them and reach the elusive 2048 tile. A puzzle that\'s easy to learn, hard to master.',
    category: 'puzzle',
    thumbnail: 'linear-gradient(135deg, #f1c40f 0%, #f39c12 100%)',
    file: 'games/2048.html',
    difficulty: 'Medium',
    emoji: '\ud83d\udd22',
    createdAt: '2026-04-09',
  },
  {
    id: 'space-invaders',
    title: 'Space Invaders',
    description: 'Defend Earth from waves of descending aliens! Shoot fast and dodge enemy fire in this iconic arcade shooter.',
    category: 'action',
    thumbnail: 'linear-gradient(135deg, #2c3e50 0%, #8e44ad 100%)',
    file: 'games/invaders.html',
    difficulty: 'Hard',
    emoji: '\ud83d\udc7e',
    createdAt: '2026-04-08',
  },
];

const GAME_CATEGORIES = {
  all:      { label: 'All Games',    icon: '\ud83c\udfae' },
  puzzle:   { label: 'Puzzle',       icon: '\ud83e\udde9' },
  action:   { label: 'Action',       icon: '\u26a1' },
  strategy: { label: 'Strategy',     icon: '\u265f\ufe0f' },
  classic:  { label: 'Classic',      icon: '\ud83d\udd79\ufe0f' }
};

const DIFFICULTY_ORDER = { 'Easy': 1, 'Medium': 2, 'Hard': 3 };
