const GAMES = [
  {
    id: 'coffee-2026-05-04',
    title: 'Espresso Pressure',
    description: 'Master the perfect espresso shot. Control the pressure gauge, ride pump surges, and avoid channeling. Keep the needle in the green sweet spot to build combo multipliers and fill your cup with golden crema.',
    category: 'action',
    thumbnail: 'assets/images/game-coffee-2026-05-04.png',
    file: 'games/coffee-2026-05-04.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-05-04',
  },

  {
    id: 'coffee-2026-05-03',
    title: 'Milk Steamer',
    description: 'Steam milk to microfoam perfection. Watch the thermometer and stop at exactly the right temperature -- no scorching allowed!',
    category: 'action',
    thumbnail: 'assets/images/game-coffee-2026-05-03.png',
    file: 'games/coffee-2026-05-03.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-05-03',
  },

  {
    id: 'coffee-2026-05-02',
    title: 'Roast Runner',
    description: 'Keep the beans moving through the roaster! Dodge hotspots, control airflow, and eject each batch at the perfect roast level.',
    category: 'action',
    thumbnail: 'assets/images/game-roast-runner.png',
    file: 'games/coffee-2026-05-02.html',
    difficulty: 'Hard',
    emoji: '',
    createdAt: '2026-05-02',
  },

  {
    id: 'caffeine-catch',
    title: 'Caffeine Catch',
    description: 'Catch falling coffee beans, cups, and espresso shots in your mug. But watch out for decaf and ice cubes! Speed increases as you level up.',
    category: 'action',
    thumbnail: 'assets/images/game-caffeine-catch.png',
    file: 'games/caffeine-catch.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-05-01',
  },
  {
    id: 'snake',
    title: 'Snake',
    description: 'The classic snake game! Eat food to grow longer, but don\'t hit the walls or your own tail. Simple yet addictive.',
    category: 'classic',
    thumbnail: 'assets/images/game-snake.png',
    file: 'games/snake.html',
    difficulty: 'Easy',
    emoji: '',
    createdAt: '2026-04-15',
  },
  {
    id: 'memory-match',
    title: 'Memory Match',
    description: 'Test your memory by matching pairs of cards. Flip two at a time and find all matching pairs to win!',
    category: 'puzzle',
    thumbnail: 'assets/images/game-memory.png',
    file: 'games/memory.html',
    difficulty: 'Easy',
    emoji: '',
    createdAt: '2026-04-14',
  },
  {
    id: 'pong',
    title: 'Pong',
    description: 'The original arcade classic! Challenge a friend in this 2-player paddle game. First to score wins the round.',
    category: 'classic',
    thumbnail: 'assets/images/game-pong.png',
    file: 'games/pong.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-04-13',
  },
  {
    id: 'flappy-bird',
    title: 'Flappy Bird',
    description: 'Navigate through endless pipes by tapping to flap. Seems easy? Think again! One of the hardest casual games ever.',
    category: 'action',
    thumbnail: 'assets/images/game-flappy.png',
    file: 'games/flappy.html',
    difficulty: 'Hard',
    emoji: '',
    createdAt: '2026-04-12',
  },
  {
    id: 'tic-tac-toe',
    title: 'Tic Tac Toe',
    description: 'Classic strategy game against an unbeatable AI. Can you outsmart the computer and force a draw — or even win?',
    category: 'strategy',
    thumbnail: 'assets/images/game-tictactoe.png',
    file: 'games/tictactoe.html',
    difficulty: 'Easy',
    emoji: '',
    createdAt: '2026-04-11',
  },
  {
    id: 'breakout',
    title: 'Breakout',
    description: 'Smash bricks with a bouncing ball and paddle. Clear all the bricks to advance. A timeless arcade favorite!',
    category: 'action',
    thumbnail: 'assets/images/game-breakout.png',
    file: 'games/breakout.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-04-10',
  },
  {
    id: '2048',
    title: '2048',
    description: 'Slide numbered tiles to combine them and reach the elusive 2048 tile. A puzzle that\'s easy to learn, hard to master.',
    category: 'puzzle',
    thumbnail: 'assets/images/game-2048.png',
    file: 'games/2048.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-04-09',
  },
  {
    id: 'space-invaders',
    title: 'Space Invaders',
    description: 'Defend Earth from waves of descending aliens! Shoot fast and dodge enemy fire in this iconic arcade shooter.',
    category: 'action',
    thumbnail: 'assets/images/game-invaders.png',
    file: 'games/invaders.html',
    difficulty: 'Hard',
    emoji: '',
    createdAt: '2026-04-08',
  },
];

const GAME_CATEGORIES = {
  all:      { label: 'All Games',    icon: '' },
  puzzle:   { label: 'Puzzle',       icon: '' },
  action:   { label: 'Action',       icon: '' },
  strategy: { label: 'Strategy',     icon: '' },
classic:  { label: 'Classic',      icon: '' },
};

const DIFFICULTY_ORDER = { 'Easy': 1, 'Medium': 2, 'Hard': 3 };