const GAMES = [
  {
    id: 'coffee-2026-05-19',
    title: 'Crema Runner',
    description: 'Guide the golden crema drop through the espresso bed. Collect glowing teal bubbles and golden power bubbles, dodge channeling cracks with warning indicators, and build your combo multiplier through five escalating phases of extraction.',
    category: 'action',
    thumbnail: 'assets/images/game-coffee-2026-05-19.png',
    file: 'games/coffee-2026-05-19.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-05-19',
  },

  {
    id: 'pong-man',
    title: 'Pong-Man',
    description: 'Pong meets Pac-Man! Hit the ball past your opponent, but watch out — Pac-Man is hungry. If he eats the ball while it\'s crossing after YOUR hit, you lose the point. Use SPACE to shake the board and nudge the ball away from danger.',
    category: 'classic',
    thumbnail: 'assets/images/game-pong-man.png',
    file: 'games/pong-man.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-05-15',
  },

  {
    id: 'coffee-2026-05-14',
    title: 'Barista Blitz',
    description: 'Fulfill coffee orders before impatient customers walk out! Build each drink by selecting ingredients in the right order. Speed and accuracy build your combo multiplier through escalating levels.',
    category: 'action',
    thumbnail: 'assets/images/game-coffee-2026-05-14.png',
    file: 'games/coffee-2026-05-14.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-05-14',
  },

  {
    id: 'coffee-2026-05-13',
    title: 'Cascara Sort',
    description: 'Sort cascara berries and coffee cherries into matching cups before they overflow! Drag and drop colorful coffee fruits into the right containers, chain combos for bonus points, and race against the clock across 10 increasingly frantic levels.',
    category: 'puzzle',
    thumbnail: 'assets/images/game-coffee-2026-05-13.png',
    file: 'games/coffee-2026-05-13.html',
    difficulty: 'Easy',
    emoji: '',
    createdAt: '2026-05-13',
  },

  {
    id: 'coffee-2026-05-12',
    title: 'Barista Defense',
    description: 'Defend the Fresh Pot from waves of decaf invaders, stale pastries, and watery brews. Place coffee equipment towers along the golden path, chain combos for massive scores, and survive all 10 waves including the final Mega Latte boss.',
    category: 'strategy',
    thumbnail: 'assets/images/game-coffee-2026-05-12.png',
    file: 'games/coffee-2026-05-12.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-05-12',
  },

  {
    id: 'coffee-2026-05-11',
    title: 'Espresso Blaster',
    description: 'Pilot your espresso cup through the morning rush. Blast descending decaf beans, ice cubes, and stale pastries with steaming hot espresso shots. Collect spread, rapid, and shield power-ups, chain combos for massive score multipliers, and survive the escalating waves.',
    category: 'action',
    thumbnail: 'assets/images/game-coffee-2026-05-11.png',
    file: 'games/coffee-2026-05-11.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-05-11',
  },

  {
    id: 'coffee-2026-05-10',
    title: 'Grind Rush',
    description: 'The morning rush is here! Beans fall down three grinder lanes. Tap or press the matching key when a bean hits the cyan grind zone. Build your combo for massive scores. Three misses and the shift ends.',
    category: 'action',
    thumbnail: 'assets/images/game-coffee-2026-05-10.png',
    file: 'games/coffee-2026-05-10.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-05-10',
  },

  {
    id: 'coffee-2026-05-08',
    title: 'Bloom Spiral',
    description: 'Guide the gooseneck kettle in a perfect spiral pour-over. Stay on the glowing golden path to evenly saturate the coffee bed, build combo multipliers, and achieve flawless extraction through three phases: Bloom, First Pour, and Second Pour.',
    category: 'action',
    thumbnail: 'assets/images/game-coffee-2026-05-08.png',
    file: 'games/coffee-2026-05-08.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-05-08',
  },

  {
    id: 'coffee-2026-05-06',
    title: 'Crema Curve',
    description: 'Master the art of espresso extraction. Follow the scrolling pressure curve with your cursor to pull the perfect shot. Keep your accuracy high to build combo multipliers and fill your cup with golden crema before time runs out.',
    category: 'action',
    thumbnail: 'assets/images/game-coffee-2026-05-06.png',
    file: 'games/coffee-2026-05-06.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-05-06',
  },

  {
    id: 'coffee-2026-05-05',
    title: 'Cup Stack Cafe',
    description: 'Stack coffee cups with perfect precision. Drop each sliding cup onto the tower -- overhang gets sliced off, but a perfect center hit builds your combo multiplier. How high can you build before the tower collapses?',
    category: 'puzzle',
    thumbnail: 'assets/images/game-coffee-2026-05-05.png',
    file: 'games/coffee-2026-05-05.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-05-05',
  },

  {
    id: 'coffee-2026-05-04',
    title: 'Espresso Pressure',
    description: 'Master the perfect espresso shot. Control the pressure gauge, ride pump surges, and avoid channeling. Keep the needle in the green sweet spot to build combo multipliers and fill your cup with golden crema.',
    category: 'action',
    thumbnail: 'assets/images/game-coffee-2026-05-04.png',
    file: 'games/coffee-2026-05-04.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-05-04',
  },

  {
    id: 'coffee-2026-05-03',
    title: 'Milk Steamer',
    description: 'Steam milk to microfoam perfection. Watch the thermometer and stop at exactly the right temperature -- no scorching allowed!',
    category: 'action',
    thumbnail: 'assets/images/game-coffee-2026-05-03.png',
    file: 'games/coffee-2026-05-03.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-05-03',
  },

  {
    id: 'coffee-2026-05-02',
    title: 'Roast Runner',
    description: 'Keep the beans moving through the roaster! Dodge hotspots, control airflow, and eject each batch at the perfect roast level.',
    category: 'action',
    thumbnail: 'assets/images/game-roast-runner.png',
    file: 'games/coffee-2026-05-02.html',
    difficulty: 'Hard',
    emoji: '',
    createdAt: '2026-05-02',
  },

  {
    id: 'caffeine-catch',
    title: 'Caffeine Catch',
    description: 'Catch falling coffee beans, cups, and espresso shots in your mug. But watch out for decaf and ice cubes! Speed increases as you level up.',
    category: 'action',
    thumbnail: 'assets/images/game-caffeine-catch.png',
    file: 'games/caffeine-catch.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-05-01',
  },
  {
    id: 'snake',
    title: 'Snake',
    description: 'The classic snake game! Eat food to grow longer, but don\'t hit the walls or your own tail. Simple yet addictive.',
    category: 'classic',
    thumbnail: 'assets/images/game-snake.png',
    file: 'games/snake.html',
    difficulty: 'Easy',
    emoji: '',
    createdAt: '2026-04-15',
  },
  {
    id: 'memory-match',
    title: 'Memory Match',
    description: 'Test your memory by matching pairs of cards. Flip two at a time and find all matching pairs to win!',
    category: 'puzzle',
    thumbnail: 'assets/images/game-memory.png',
    file: 'games/memory.html',
    difficulty: 'Easy',
    emoji: '',
    createdAt: '2026-04-14',
  },
  {
    id: 'pong',
    title: 'Pong',
    description: 'The original arcade classic! Challenge a friend in this 2-player paddle game. First to score wins the round.',
    category: 'classic',
    thumbnail: 'assets/images/game-pong.png',
    file: 'games/pong.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-04-13',
  },
  {
    id: 'flappy-bird',
    title: 'Flappy Bird',
    description: 'Navigate through endless pipes by tapping to flap. Seems easy? Think again! One of the hardest casual games ever.',
    category: 'action',
    thumbnail: 'assets/images/game-flappy.png',
    file: 'games/flappy.html',
    difficulty: 'Hard',
    emoji: '',
    createdAt: '2026-04-12',
  },
  {
    id: 'tic-tac-toe',
    title: 'Tic Tac Toe',
    description: 'Classic strategy game against an unbeatable AI. Can you outsmart the computer and force a draw — or even win?',
    category: 'strategy',
    thumbnail: 'assets/images/game-tictactoe.png',
    file: 'games/tictactoe.html',
    difficulty: 'Easy',
    emoji: '',
    createdAt: '2026-04-11',
  },
  {
    id: 'breakout',
    title: 'Breakout',
    description: 'Smash bricks with a bouncing ball and paddle. Clear all the bricks to advance. A timeless arcade favorite!',
    category: 'action',
    thumbnail: 'assets/images/game-breakout.png',
    file: 'games/breakout.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-04-10',
  },
  {
    id: '2048',
    title: '2048',
    description: 'Slide numbered tiles to combine them and reach the elusive 2048 tile. A puzzle that\'s easy to learn, hard to master.',
    category: 'puzzle',
    thumbnail: 'assets/images/game-2048.png',
    file: 'games/2048.html',
    difficulty: 'Medium',
    emoji: '',
    createdAt: '2026-04-09',
  },
  {
    id: 'space-invaders',
    title: 'Space Invaders',
    description: 'Defend Earth from waves of descending aliens! Shoot fast and dodge enemy fire in this iconic arcade shooter.',
    category: 'action',
    thumbnail: 'assets/images/game-invaders.png',
    file: 'games/invaders.html',
    difficulty: 'Hard',
    emoji: '',
    createdAt: '2026-04-08',
  },
];

const GAME_CATEGORIES = {
  all:      { label: 'All Games',    icon: '' },
  puzzle:   { label: 'Puzzle',       icon: '' },
  action:   { label: 'Action',       icon: '' },
  strategy: { label: 'Strategy',     icon: '' },
classic:  { label: 'Classic',      icon: '' },
};

const DIFFICULTY_ORDER = { 'Easy': 1, 'Medium': 2, 'Hard': 3 };